### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by flpfar** [Zubenna/group_our_transportation#2]
Great job so far!

There are some details you may consider improving:
- You don't need an image for transportation. It should have the icon from the group.
- Create a field 'group_id' in Transportation. So you can link the transportation to a group.
- Use a select field to select a group in a 'New Transportation'
- Re-check the layout specifications, maybe it should be only mobile.

Keep the great job!

**Comment by Zubenna** [comment]
Recommendations have been implemented.
